application: mytelco
version: 0-1-demo
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /.*
  script: mytelco.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
